### ISSUE TITLE
Effect of pT cuts on visible tau decay products

### ISSUE THREAD

**Issue by veelken** [HEP-KBFI/tautau-Entanglement#1]
The attached plots show the effect of applying pT cuts on the charged pions produced in e+ e- -> tau+ tau- -> pi- nu pi+ nu decays at Belle. The plots demonstrate that there is no chance to correct for this bias with the KNN method (since ALL events with low C_kk are removed by the pT cut, there are no events left to which a weight correction can be applied)

**Comment by veelken** [comment]
![makeRecoEffectPlots_C_kk_minVisTauPt](https://github.com/HEP-KBFI/tautau-Entanglement/assets/4981326/c999827d-6f68-44a8-a7f6-6d8dfa01f517)
![makeRecoEffectPlots_C_nn_minVisTauPt](https://github.com/HEP-KBFI/tautau-Entanglement/assets/4981326/574e9085-547c-4287-9551-df02cf1a60d1)
![makeRecoEffectPlots_C_rr_minVisTauPt](https://github.com/HEP-KBFI/tautau-Entanglement/assets/4981326/b5e2ea8b-dac7-4598-bd8e-e3257e08977d)

**Comment by veelken** [comment]
Closing the issue, as I believe the case of using the KNN method to correct for the selection bias is closed.

**Comment by ktht** [comment]
The issue is resolved, no?
